# parameters
nc: 1
groupnorm: True
encoder: {'type': ContextConditioning, 'params': {'sequenceencoder': "transformer", 'n_lstm_layers': 1, 'activation': nn.ELU,
                                                  'zdim': 64, 'normalize_input': True}}
# anchors
anchors: 
  - [11,26,  11,34,  11,45]  # P3/8

# YOLO backbone
backbone:
  # [from, number, module, args]
  [[-1, Conv, [16, 3]],  # 0-P1/2
   [-1, Conv, [32, 3, 2]],  # 1-P2/4
   [-1, C2f, [64, True]],
   [-1, Conv, [64, 3, 2]],  # 3-P3/8
   [-1, C2f, [64, True]],
   [-1, FiLMConv, [128, 3, 2]],  # 5-P4/16
   [-1, C2f, [128, True]],
   [-1, FiLMConv, [128, 3, 2]],  # 7-P5/32
   [-1, C2f, [128, True]],
  ]

# YOLO head
head:
  [[-1, FiLMConv, [128, 3, 1]],
   [-1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], Concat, [1]],  # cat backbone P4
   [-1, C2f, [128]],

   [-1, FiLMConv, [128, 3, 1]],
   [-1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], Concat, [1]],  # cat backbone P3
   [-1, C2f, [128]],

   [[16, 16, 16], Detect, [nc, anchors]],  # Detect(P3, P4)
  ]
